In [69]:
import numpy as np

In [2]:
a = [1, 2, 5, 59, 69]

In [3]:
arr = np.array(a)

In [4]:
arr

array([ 1,  2,  5, 59, 69])

In [5]:
arr.shape

(5,)

In [6]:
arr.dtype

dtype('int32')

## Array creation methods

In [7]:
listarray = np.array([[1 ,2, 3], [4, 5, 6], [7, 8, 9]])

In [8]:
listarray.shape

(3, 3)

In [9]:
listarray.size

9

In [10]:
np.array({88, 78, 99})

array({88, 99, 78}, dtype=object)

In [11]:
zeroes = np.zeros((2, 5))

In [12]:
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
lspace = np.linspace(1, 2, 5)

In [15]:
lspace

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [16]:
np.empty((4, 6))  #Gives random array

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.24610994e-306, 1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 1.86921143e-306],
       [6.23061763e-307, 8.90104239e-307, 6.89804132e-307,
        1.22387465e-307, 1.42418172e-306, 2.04712906e-306],
       [7.56589622e-307, 1.11258277e-307, 8.90111708e-307,
        3.22643519e-307, 9.79103798e-307, 2.46155235e-312]])

In [17]:
emp_like = np.empty_like(lspace)

In [18]:
emp_like

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [19]:
#Gives identity matrix of given order

ide = np.identity(45)
print(ide)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [20]:
arr = np.arange(36)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [22]:
arr.reshape(3, 12) 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [23]:
# Makes the given array 1 dimensional
arr = arr.ravel()

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [25]:
x = np.array([[1, 2, 3], [4, 5, 6], [9, 8, 77]])

In [26]:
x.sum()

115

In [27]:
x.sum(axis = 0)

array([14, 15, 86])

In [28]:
x = x.T

In [29]:
x

array([[ 1,  4,  9],
       [ 2,  5,  8],
       [ 3,  6, 77]])

In [30]:
x.flat?

Type:        flatiter
String form: <numpy.flatiter object at 0x000001D01D15D190>
Length:      9
File:        c:\users\dell\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
Flat iterator object to iterate over arrays.

A `flatiter` iterator is returned by ``x.flat`` for any array `x`.
It allows iterating over the array as if it were a 1-D array,
either in a for-loop or by calling its `next` method.

Iteration is done in row-major, C-style order (the last
index varying the fastest). The iterator can also be indexed using
basic slicing or advanced indexing.

See Also
--------
ndarray.flat : Return a flat iterator over an array.
ndarray.flatten : Returns a flattened copy of an array.

Notes
-----
A `flatiter` iterator can not be constructed directly from Python code
by calling the `flatiter` constructor.

Examples
--------
>>> x = np.arange(6).reshape(2, 3)
>>> fl = x.flat
>>> type(fl)
<class 'numpy.flatiter'>
>>> for item in fl:
...     print(item)
...
0
1
2
3
4
5

>>> fl[2:4]
a

In [31]:
it = x.flat

In [32]:
it

In [33]:
for ele in it:
    print(ele)

1
4
9
2
5
8
3
6
77


In [34]:
x.ndim #gives dimension of the array

2

In [35]:
one = np.array([1, 5, 44, 8, 7, 99, 0])

In [36]:
#returns the index of the maximum and minimum element in the array
print(one.argmin())
one.argmax()

6


5

In [37]:
#returns a array of indexes of sorted array
one.argsort()

array([6, 0, 1, 4, 3, 2, 5], dtype=int64)

In [38]:
x.argmin()

0

In [39]:
x.argmax()

8

In [40]:
x.argmax(axis = 0)

array([2, 2, 2], dtype=int64)

In [41]:
x.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [42]:
one.reshape(7, 1)

array([[ 1],
       [ 5],
       [44],
       [ 8],
       [ 7],
       [99],
       [ 0]])

In [43]:
x+x.T

array([[  2,   6,  12],
       [  6,  10,  14],
       [ 12,  14, 154]])

In [44]:
x*x.T

array([[   1,    8,   27],
       [   8,   25,   48],
       [  27,   48, 5929]])

In [45]:
np.sqrt(x)

array([[1.        , 2.        , 3.        ],
       [1.41421356, 2.23606798, 2.82842712],
       [1.73205081, 2.44948974, 8.77496439]])

In [46]:
np.where(x>2)

(array([0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 1, 2, 0, 1, 2], dtype=int64))

In [47]:
np.count_nonzero(x)

9

In [48]:
np.nonzero(x)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [49]:
import sys

In [50]:
py_ar = [0, 4, 5, 6]

np_ar = np.array(py_ar)

In [51]:
sys.getsizeof(1) * len(py_ar)

112

In [52]:
np_ar.itemsize * np_ar.size

16

In [53]:
b = np.array([[[1, 3], [9, 5], [78, 67]]])

In [54]:
b

array([[[ 1,  3],
        [ 9,  5],
        [78, 67]]])

In [55]:
b[0, 1, 1]

5

In [56]:
np.full((2, 4), 69)

array([[69, 69, 69, 69],
       [69, 69, 69, 69]])

In [57]:
np.random.rand(4,3)

array([[0.45576342, 0.42995609, 0.56907712],
       [0.55429748, 0.64461334, 0.13994524],
       [0.28947512, 0.84910342, 0.52271081],
       [0.27018617, 0.14770999, 0.35972268]])

In [58]:
np.random.randint(7, size=(3, 3))

array([[0, 3, 0],
       [1, 6, 3],
       [6, 5, 1]])

In [59]:
a1 = np.repeat(b, 2)

In [60]:
a1

array([ 1,  1,  3,  3,  9,  9,  5,  5, 78, 78, 67, 67])

In [61]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Linear Algebra

In [62]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [63]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [64]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

In [65]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [67]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [68]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [70]:
a = np.random.randint(10, size=(3,3))

In [71]:
a

array([[7, 8, 0],
       [1, 2, 1],
       [3, 1, 0]])

In [75]:
print(a[:2, 1:])

[[8 0]
 [2 1]]
